# Generated by Django 5.2.5 on 2025-08-13 11:41

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('img', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='images/')),
                ('document', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage, upload_to='file/')),
                ('audio', models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage, upload_to='audio/')),
                ('video', models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage, upload_to='video/')),
            ],
        ),
    ]
